**** everything, we're going doing five retries

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -36,13 +36,14 @@ jobs:
       - name: Run server
         run: npm run test:server &
       - name: Run e2e tests for chrome
+        ## Retire up to 5 times as tests on GitHub Actions are flakey :-(
         run: |
-          for i in 1 2 3; do
+          for i in 1 2 3 4 5; do
             echo "Attempt #$i"
             if npm run test:e2e -- --browsers=chrome; then
               exit 0
             fi
-            echo "Retry #$i failed, retrying in 5 seconds..." >&2
+            echo "Attempt #$i failed" >&2
             sleep 5
           done
           echo "All attempts failed."
@@ -64,16 +65,17 @@ jobs:
       - name: Run server
         run: npm run test:server &
       - name: Run e2e tests for firefox
+        ## Retire up to 5 times as tests on GitHub Actions are flakey :-(
         run: |
-          for i in 1 2 3; do
+          for i in 1 2 3 4 5; do
             echo "Attempt #$i"
             if npm run test:e2e -- --browsers=firefox; then
               exit 0
             fi
-            echo "Retry #$i failed, retrying in 5 seconds..." >&2
+            echo "Attempt #$i failed" >&2
             sleep 5
           done
-          echo "All attempts failed."
+          echo "All attempts failed"
           exit 1
   safari-tests:
     name: Run Safari e2e tests
@@ -92,14 +94,15 @@ jobs:
       - name: Run server
         run: npm run test:server &
       - name: Run e2e tests for safari
+        ## Retire up to 5 times as tests on GitHub Actions are flakey :-(
         run: |
-          for i in 1 2 3; do
+          for i in 1 2 3 4 5; do
             echo "Attempt #$i"
             if npm run test:e2e -- --browsers=safari; then
               exit 0
             fi
-            echo "Retry #$i failed" >&2
+            echo "Attempt #$i failed" >&2
             sleep 5
           done
-          echo "All attempts failed."
+          echo "All attempts failed"
           exit 1
